### ISSUE TITLE
Path to Backfill 2023 MT Legislative Session

### ISSUE THREAD

**Issue by whargrove** [OpenMontana/montana-legislature-council-data-project#72]
Goal: Run event gather for all videos since March 15, 2023 in the 2023 MT Legislative Session.

Problem(s):
1. Event gather will fail frequently due to no resources available in Google Cloud.
2. Event gather will fail due to container killed from out of memory (and sometimes disk space).

Mitigations:
1. 499e3c3 added retry, so the individual task will retry for ~6 hours waiting for resources. This isn't a perfect since since the job can still block on lack of resources.
2. A fork of CouncilDataProject/cdp-backend to make event ingestion more efficient. (https://github.com/CouncilDataProject/cdp-backend/issues/230 discusses some of the reasons why more efficiency is needed.)

Tasks:
- [x] Fork CouncilDataProject/cdp-backend -> OpenMontana/cdp-backend
- [x] Publish (https://github.com/OpenMontana/cdp-backend/commit/790825c77bebb6e2274324a3d39816f80ae323b7) fork to OpenMontana/cdp-backend on PyPi.
- [ ] Refactor [event_gather_pipeline.py](https://github.com/OpenMontana/cdp-backend/blob/790825c77bebb6e2274324a3d39816f80ae323b7/cdp_backend/pipeline/event_gather_pipeline.py) so that `create_event_gather_flow` returns `List[Flow]`. A Flow should be returned for _each_ event that is processed by the event gather processing pipeline. (2h)
- [ ] Refactor [run_cdp_event_gather.py](https://github.com/OpenMontana/cdp-backend/blob/790825c77bebb6e2274324a3d39816f80ae323b7/cdp_backend/bin/run_cdp_event_gather.py) to run each flow returned from `create_event_gather_flow` sequentially. (.5h)
- [ ] Release a new version of the OpenMontana/cdp-backend fork to PyPi. (Tagging a release in the repo should automatically trigger an action to publish the artifact.) (.5h)
- [ ] Replace this repo's dependency of CouncilDataProject/cdp-backend with the OpenMontana fork. ( .25h)
- [ ] Use GitHub Action: Event Gather to trigger a manual gather, using time range for the day of March 15, 2023 to backfill. Verify the action runs successfully and events are ingested for March 15, 2023. (Press a button, but if it fails then 1-2h to debug the failure.)
- [ ] Backfill remaining days. (Consider using larger time frames to reduce the amount of actual job runs that are needed. I'd suggest starting with 3-day batches and if that works try to crank up to 5-day so that each action run can process 1-work week. Most of this time is waiting for the job to run/finish and then potentially debugging the failure if any. It could be some babysitting or 1-2h per job failure.) 
- [ ] Disable the event gather scheduled action in this repo. (.5h)

For local or manual testing, these tasks may be needed to process events without scraping each time (faster feedback loop):

- [ ] Read a JSON file of EventIngestionModel in [run_cdp_event_gather.py](https://github.com/OpenMontana/cdp-backend/blob/790825c77bebb6e2274324a3d39816f80ae323b7/cdp_backend/bin/run_cdp_event_gather.py) and pass the List[EventIngestionModel] to `create_event_gather_flow`.
- [ ] Generate a JSON file for each day that needs to be backfilled. In this repo, update [`scraper.py`](https://github.com/OpenMontana/montana-legislature-council-data-project/blob/044bf23a24acb8bd62145a56078a4a4571638cb8/python/cdp_montana_legislature_backend/scraper.py) so that it can output JSON to stdout.

**Comment by evamaxfield** [comment]
Upgrade cdp-backend to v4.1.0.rc0 -- it has the reduced complexity pipeline. It has been tested on the Seattle instance: https://github.com/CouncilDataProject/seattle/actions/runs/4902430069/jobs/8754315894

Hopefully it works for you.

On the backfill stuff. You can do the backfill via GitHub UI directly or can use https://github.com/CouncilDataProject/cdp-gh-utils

Good luck.

**Comment by whargrove** [comment]
Amazing! Thank you @evamaxfield. I will try out v4.1.0.rc0 here.

Also, didn't know about the backfill utils, those are super helpful!

**Comment by whargrove** [comment]
The CML runner did not crash due to memory, but the GitHub action job timed-out at 6h. Increased the GH job timeout to 24h.

**Comment by whargrove** [comment]
Opened https://github.com/CouncilDataProject/cdp-backend/issues/233 for the duplicate encode issue.

**Comment by whargrove** [comment]
Closing this issue since the core tasks are addressed.
